"""Define the test-generation task assigned to the Tester Agent."""

from __future__ import annotations

import os

from crewai import Task

from agents.tester import tester

CURRENT_DIRECTORY = os.path.dirname(__file__)
BACKEND_DIRECTORY = os.path.dirname(CURRENT_DIRECTORY)
OUTPUT_DIRECTORY = os.path.join(BACKEND_DIRECTORY, "output")
GENERATED_CODE_FILE_NAME = "generated_code.py"
GENERATED_CODE_PATH = os.path.join(OUTPUT_DIRECTORY, GENERATED_CODE_FILE_NAME)
TEST_SUITE_FILE_NAME = "test_suite.py"
TEST_SUITE_PATH = os.path.join(OUTPUT_DIRECTORY, TEST_SUITE_FILE_NAME)
TASK_DESCRIPTION_TEMPLATE = (
    "You are given Python code that was generated by another agent.\n"
    "Generated code under test:\n"
    "{generated_code}\n\n"
    "Instructions:\n"
    "- Read the code provided.\n"
    "- Write a complete pytest suite.\n"
    "- Cover happy path behavior, null inputs, boundary values, and type errors.\n"
    "- Use type hints and docstrings in test functions.\n"
    "- Return ONLY valid Python test code.\n"
    "- Do not include markdown fences, prose, or explanations."
)
EXPECTED_OUTPUT = (
    "A complete pytest file saved to output/test_suite.py that thoroughly validates "
    "the provided generated code, including happy path, null inputs, boundary values, "
    "and type error scenarios."
)


def load_generated_code() -> str:
    """Load generated source code from output/generated_code.py."""
    with open(GENERATED_CODE_PATH, "r", encoding="utf-8") as code_file:
        return code_file.read()


def create_test_code_task(generated_code: str | None = None) -> Task:
    """Create a Tester task from generated code content."""
    code_content = generated_code if generated_code is not None else load_generated_code()
    return Task(
        description=TASK_DESCRIPTION_TEMPLATE.format(generated_code=code_content),
        expected_output=EXPECTED_OUTPUT,
        agent=tester,
        output_file=TEST_SUITE_PATH,
    )


test_code_task = create_test_code_task
